#!/usr/bin/perl

`cd bin; rm -rf *`;
`mkdir bin/manticore`;
`mkdir bin/manticore/dl`;
`cd src; jflex Lexer.lex; bison YYParser.y`;
`cd src; javac *.java dl/*.java;`;
`mv src/*.class bin;`;
`mv src/dl/*.class bin/manticore/dl/`;


#@dlfiles = `ls src/dl/*.java`;
#chomp(@dlfiles);
#
#foreach (@dlfiles) {
#	print $_
#}


