#!/usr/bin/perl

`cd bin; rm -rf *`;
`mkdir bin/manticore`;
`mkdir bin/manticore/dl`;
`mkdir bin/manticore/symbolicexecution`;
`mkdir bin/manticore/matlabkit`;
`cd src; jflex Lexer.lex; bison YYParser.y`;
`cd src/dl; ./GenerateNativeInterpretation`;
`cd src; javac *.java dl/*.java symbolicexecution/*.java`;
`cp src/matlabkit/*.m bin/manticore/matlabkit/`;
`mv src/*.class bin;`;
`mv src/dl/*.class bin/manticore/dl/`;
`mv src/symbolicexecution/*.class bin/manticore/symbolicexecution/`;


#@dlfiles = `ls src/dl/*.java`;
#chomp(@dlfiles);
#
#foreach (@dlfiles) {
#	print $_
#}


