#!/usr/bin/perl

use FindBin;

$ENV{"MANTICORE2"} = "$FindBin::Bin";
$ENV{"MATLABKIT"} = "manticore/matlabkit";
$ENV{"SYMBOLICEXECUTION"} = "manticore/symbolicexecution";
$ENV{"MATLABSAMPLINGKIT"} = "manticore/matlabsamplingkit";
$ENV{"MATLABSIMULATIONKIT"} = "manticore/matlabsimulationkit";
$ENV{"DL"} = "manticore/dl";
$ENV{"PROTEUS"} = "/home/nikos/Programs/proteus";

`cd bin; rm -rf *`;
`mkdir bin/manticore`;

`mkdir bin/proteus`;
`mkdir bin/proteus/dl`;
`mkdir bin/proteus/dl/parser`;
`mkdir bin/proteus/dl/syntax`;
`mkdir bin/proteus/dl/semantics`;

`mkdir bin/manticore/symbolicexecution`;
`mkdir bin/manticore/matlabkit`;
`mkdir bin/manticore/matlabsimulationkit`;
`mkdir bin/manticore/matlabsamplingkit`;
`mkdir bin/manticore/matlabsamplingkit/lyapunovsearch`;

# Compile
`cd \$PROTEUS/src/dl/parser; jflex dLLexer.lex; bison dLParser.y`;
`cd \$PROTEUS/src/dl/semantics; ./GenerateNativeInterpretation`;
`cd src; javac *.java \$PROTEUS/src/dl/parser/*.java \$PROTEUS/src/dl/syntax/*.java \$PROTEUS/src/dl/semantics/*.java symbolicexecution/*.java matlabsimulationkit/*.java matlabsamplingkit/*.java`; #keymaerakit/*.java`;

# Organize
`cp src/matlabsimulationkit/*.m bin/manticore/matlabsimulationkit/`;
`cp src/matlabkit/*.m bin/manticore/matlabkit/`;
`cp -R src/matlabsamplingkit/lyapunovsearch/* bin/manticore/matlabsamplingkit/lyapunovsearch/`;
`mv src/*.class bin;`;

`mv \$PROTEUS/src/dl/parser/*.class bin/proteus/dl/parser/`;
`mv \$PROTEUS/src/dl/syntax/*.class bin/proteus/dl/syntax/`;
`mv \$PROTEUS/src/dl/semantics/*.class bin/proteus/dl/semantics/`;

`mv src/matlabsimulationkit/*.class bin/manticore/matlabsimulationkit/`;
`mv src/matlabsamplingkit/*.class bin/manticore/matlabsamplingkit/`;
`mv src/symbolicexecution/*.class bin/manticore/symbolicexecution/`;

`cp etc/run bin/run`;


#@dlfiles = `ls src/dl/*.java`;
#chomp(@dlfiles);
#
#foreach (@dlfiles) {
#	print $_
#}


